Targets:
  #  PXBoardQP4G:
  #    Name: PXBoardQP4G
  #    TargetImage: assets/images/PXBoardQP4G-2022-10-19.img
  #    SkipUpdate: False
  #    Assets:
  #      BaseImage:
  #        path: assets/images/updated.img
  #
  PXBoardQ2G:
    Name: PXBoardQ2G
    TargetImage: assets/images/PXBoardQ2G-2022-10-20.img
    SkipUpdate: False
    Assets:
      BaseImage:
        path: assets/images/updated.img

BuildCommand:
  cmd: helper_scripts/build_img.sh
  params:
    - BaseImage
    - TargetImage
    - U-Boot
    - RootFS
    - Packages
    - Scripts
